---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - /${APPS_PATH}/calibre-web-automated:/config
      - /${BASE_PATH}/media/books/calibre:/calibre-library
      # - /${BASE_PATH}/media/books/processing:/cwa-book-ingest
    ports:
      - 31067:8083
    restart: unless-stopped
