---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /${BASE_PATH}/docker/radarr/config:/config
      - /${BASE_PATH}/media/video/Plex:/media #optional
      - /${BASE_PATH}/docker/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
