version: "2"
services:
  rss-bridge:
    container_name: rssbridge
    image: rssbridge/rss-bridge:latest
    volumes:
      - /${APPS_PATH}/rssbridge:/config
    ports:
      - 33000:80
    restart: unless-stopped
